/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.edu.megatrend.dnevnik;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nikola
 */
public class dStarateljiDodavanje extends javax.swing.JDialog {
    String id_ucenika;
    /**
     * Creates new form dRoditelji
     */
    public dStarateljiDodavanje(java.awt.Frame parent, boolean modal, String id) {
        super(parent, modal);
        id_ucenika = id;
        initComponents();
    }

    private ResultSet dodajStaratelja(
            String sIme,
            String sPrezime,
            String sTelefon,
            String sAdresa,
            String sEmail,
            String sStrucnaSprema,
            String sNapomena) {
        if (allreadyInTable(sIme, sPrezime, sTelefon, sAdresa, sEmail, sStrucnaSprema, sNapomena) == false) {
            fLog.CB.izvrsiQueryBezRezultata(
                    "INSERT INTO roditelj VALUES ($next_id,'" + sIme + "','" + sPrezime + "','"
                    + sTelefon + "', '" + sAdresa + "', '" + sEmail + "', ' " + sStrucnaSprema + "', '" + sNapomena + "') ");
            
            
            //ATTENTION
            return fLog.CB.izvrsiQuery("SELECT last_insert_rowid() FROM roditelj");
        } else {
            return fLog.CB.izvrsiQuery("SELECT id_roditelj FROM roditelj WHERE ime ='"
                    +sIme+"', prezime ='"+sPrezime+"',adresa ="+sAdresa+"') "); 
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfIme1 = new javax.swing.JTextField();
        tfPrezime1 = new javax.swing.JTextField();
        tfTelefon1 = new javax.swing.JTextField();
        tfAdresa1 = new javax.swing.JTextField();
        tfEmail1 = new javax.swing.JTextField();
        tfStrucnaSprema1 = new javax.swing.JTextField();
        tfNapomena1 = new javax.swing.JTextField();
        tfIme2 = new javax.swing.JTextField();
        tfPrezime2 = new javax.swing.JTextField();
        tfTelefon2 = new javax.swing.JTextField();
        tfAdresa2 = new javax.swing.JTextField();
        tfEmail2 = new javax.swing.JTextField();
        tfStrucnaSprema2 = new javax.swing.JTextField();
        tfNapomena2 = new javax.swing.JTextField();
        btnDodajStaratelje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Staratelj 1:");

        jLabel2.setText("Staratelj 2:");

        jLabel3.setText("Ime");

        jLabel4.setText("Prezime");

        jLabel5.setText("Telefon");

        jLabel6.setText("Adresa");

        jLabel7.setText("email");

        jLabel8.setText("Str.spr");

        jLabel9.setText("Napomena");

        tfIme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIme1ActionPerformed(evt);
            }
        });

        tfTelefon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefon1ActionPerformed(evt);
            }
        });

        tfAdresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAdresa1ActionPerformed(evt);
            }
        });

        tfNapomena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNapomena1ActionPerformed(evt);
            }
        });

        tfPrezime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrezime2ActionPerformed(evt);
            }
        });

        btnDodajStaratelje.setText("Dodaj staratelje");
        btnDodajStaratelje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStarateljeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNapomena1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(tfStrucnaSprema1)
                            .addComponent(tfEmail1)
                            .addComponent(tfAdresa1)
                            .addComponent(tfTelefon1)
                            .addComponent(tfPrezime1)
                            .addComponent(tfIme1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDodajStaratelje)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfIme2)
                                .addComponent(tfPrezime2)
                                .addComponent(tfTelefon2)
                                .addComponent(tfAdresa2)
                                .addComponent(tfEmail2)
                                .addComponent(tfStrucnaSprema2)
                                .addComponent(tfNapomena2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfIme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIme2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfPrezime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrezime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTelefon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTelefon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfAdresa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAdresa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfStrucnaSprema1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfStrucnaSprema2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfNapomena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNapomena2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDodajStaratelje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIme1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIme1ActionPerformed

    private void tfTelefon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefon1ActionPerformed

    private void tfAdresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAdresa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAdresa1ActionPerformed

    private void tfPrezime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrezime2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrezime2ActionPerformed

    private void tfNapomena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNapomena1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNapomena1ActionPerformed

    private void btnDodajStarateljeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStarateljeActionPerformed
        // TODO add your handling code here:
        ResultSet rs1 = this.dodajStaratelja(tfIme1.getText(), tfPrezime1.getText(),
                tfTelefon1.getText(), tfAdresa1.getText(), tfEmail1.getText(),
                tfStrucnaSprema1.getText(), tfNapomena1.getText());
        try {
            String id_staratelja1 = rs1.getNString(1);
            fLog.CB.izvrsiQueryBezRezultata(
                "UPDATE ucenik SET "
                        + "staratelj1 = " + id_staratelja1
                        + "WHERE id_ucenik = " + id_ucenika);            
        } catch (SQLException ex) {
            Logger.getLogger(dStarateljiDodavanje.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultSet rs2 = this.dodajStaratelja(tfIme2.getText(), tfPrezime2.getText(),
                tfTelefon2.getText(), tfAdresa2.getText(), tfEmail2.getText(),
                tfStrucnaSprema2.getText(), tfNapomena2.getText());
        try {
            String id_staratelja2 = rs2.getNString(1);
            fLog.CB.izvrsiQueryBezRezultata(
                "UPDATE ucenik SET "
                        + "staratelj2 = " + id_staratelja2
                        + "WHERE id_ucenik = " + id_ucenika);            
        } catch (SQLException ex) {
            Logger.getLogger(dStarateljiDodavanje.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnDodajStarateljeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dStarateljiDodavanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dStarateljiDodavanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dStarateljiDodavanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dStarateljiDodavanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dStarateljiDodavanje dialog = new dStarateljiDodavanje(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStaratelje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfAdresa1;
    private javax.swing.JTextField tfAdresa2;
    private javax.swing.JTextField tfEmail1;
    private javax.swing.JTextField tfEmail2;
    private javax.swing.JTextField tfIme1;
    private javax.swing.JTextField tfIme2;
    private javax.swing.JTextField tfNapomena1;
    private javax.swing.JTextField tfNapomena2;
    private javax.swing.JTextField tfPrezime1;
    private javax.swing.JTextField tfPrezime2;
    private javax.swing.JTextField tfStrucnaSprema1;
    private javax.swing.JTextField tfStrucnaSprema2;
    private javax.swing.JTextField tfTelefon1;
    private javax.swing.JTextField tfTelefon2;
    // End of variables declaration//GEN-END:variables

    private boolean allreadyInTable(String sIme, String sPrezime, String sTelefon, String sAdresa, String sEmail, String sStrucnaSprema, String sNapomena) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
