package rs.edu.megatrend.dnevnik;

import java.awt.Toolkit;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ljubo
 */
public class fLog extends javax.swing.JFrame {

    //kada se unese pogresan user ili pass, treba da se isprazne polja i da se fokus
    //postavi na polje za username
    private void isprazniPolja()
    {
        tfUser.setText(null);
        pfPass.setText(null);
        tfUser.requestFocus();
    }
    
    /**
     * Creates new form fLog
     */
    public fLog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUloguj = new javax.swing.JButton();
        tfUser = new javax.swing.JTextField();
        pfPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Podešavanja");
        setIconImage(Toolkit.getDefaultToolkit().getImage(fLog.class.getResource("logo.png")));
        setResizable(false);

        btnUloguj.setText("Uloguj se");
        btnUloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlogujActionPerformed(evt);
            }
        });

        jLabel1.setText("Korisničko ime");

        jLabel2.setText("Šifra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUloguj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfUser)
                    .addComponent(pfPass))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUloguj)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUlogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlogujActionPerformed
//        //gde god se koristi resultset mora se staviti try catch blok za SQLException
//        //ne mora oko celog bloka, moze samo oko dela u kom se spominje resultset
//        try 
//        {
//            //getpassword funkcija ne vraca cist string, pa ga je potrebno pretvoriti u obican string
//            String sifra = new String(pfPass.getPassword());
//            
//            ResultSet rs = ConnectionBase.izvrsiQuery("SELECT komentar FROM koris WHERE fuser = '"+tfUser.getText()+"' AND pass = '"+ ConnectionBase.string2md5(sifra) +"'");
//            //da ne bi ostajala vrednost sifre u ram memoriji, odmah se postavlja na null
//            sifra = null;
//            int brojRedova = 0;
//            //rs.first();  //postgresql ne podrzava scrollable resultset, i zato se mora ici sa rs.next
//            while (rs.next())
//            {
//                if (!rs.getString("komentar").equals("admin"))
//                {
//                    JOptionPane.showMessageDialog(null, "Niste autorizovani da pristupite ovom programu.");
//                    isprazniPolja();
//                }
//                else
//                {
        ResultSet rs = ConnectionBase.izvrsiQuery("SELECT * from ucenik");
                    fMeni newfm = new fMeni();
                    newfm.setLocationRelativeTo(this);
                    newfm.setVisible(true);
                    /*fPregledLekara newfpl = new fPregledLekara();
                    newfpl.setLocationRelativeTo(this);
                    newfpl.ucitajLekare();
                    newfpl.setVisible(true);*/
                    this.setVisible(false);
//                }
//                brojRedova++;
//            }
//            
//            if (brojRedova == 0)
//            {
//                JOptionPane.showMessageDialog(null, "Pogrešan username ili password.");
//                isprazniPolja();
//            }
//            //conn.close();
//        } 
//        catch (SQLException ex) {
//            Logger.getLogger(fLog.class.getName()).log(Level.SEVERE, null, ex);
//        } 
    }//GEN-LAST:event_btnUlogujActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                //izmenio sam metodu run tako da se pravi novi fLog pod imenom
                //newfLog, da bi onda njemu mogao da kazem setLocationRelativeTo(null)
                //sto ce ga staviti na sredinu ekrana (bez prvog iscrtavanja u levom cosku, pa tek onda da se prebaci na sredinu)
                //ovo je potrebno uraditi za prvi JFrame, svaki sledeci moze da se ne otvara iz run-a
                //vec iz neke druge metode, a i za druge ne treba prosledjivati null nego this
                fLog newfLog = new fLog();
                newfLog.setLocationRelativeTo(null);
                //prikazivanje newfLoga
                newfLog.setVisible(true);                        
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUloguj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
